import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const sqlFile = path.resolve(__dirname, '../../database/System_Restaurant.sql');

// --- DETERMINISTIC PRNG ---
class LCG {
    constructor(seed) { this.seed = seed; this.a = 1664525; this.c = 1013904223; this.m = Math.pow(2, 32); }
    next() { this.seed = (this.a * this.seed + this.c) % this.m; return this.seed / this.m; }
    nextRange(min, max) { return Math.floor(this.next() * (max - min + 1)) + min; }
    nextElement(arr) { return arr[this.nextRange(0, arr.length - 1)]; }
    chance(probability) { return this.next() < probability; }
}
const prng = new LCG(42);

// --- STATIC DATA (Extracted from System_Restaurant.sql) ---
const tables = [
    { table_id: 1, capacity: 2 }, { table_id: 2, capacity: 4 }, { table_id: 3, capacity: 6 }, { table_id: 4, capacity: 8 },
    { table_id: 5, capacity: 6 }, { table_id: 7, capacity: 6 }, { table_id: 8, capacity: 4 }, { table_id: 9, capacity: 4 },
    { table_id: 11, capacity: 4 }, { table_id: 12, capacity: 4 }, { table_id: 13, capacity: 4 }, { table_id: 15, capacity: 4 },
    { table_id: 16, capacity: 4 }, { table_id: 17, capacity: 4 }, { table_id: 18, capacity: 4 }, { table_id: 19, capacity: 4 },
    { table_id: 20, capacity: 4 }, { table_id: 21, capacity: 4 }, { table_id: 22, capacity: 4 }, { table_id: 23, capacity: 4 },
    { table_id: 25, capacity: 4 }, { table_id: 26, capacity: 6 }, { table_id: 27, capacity: 8 }, { table_id: 28, capacity: 4 },
    { table_id: 29, capacity: 4 }, { table_id: 30, capacity: 4 }, { table_id: 31, capacity: 4 }
];

const dishes = [
    { dish_id: 1, price: 168000 }, { dish_id: 2, price: 428000 }, { dish_id: 3, price: 188000 }, { dish_id: 4, price: 228000 },
    { dish_id: 5, price: 168000 }, { dish_id: 6, price: 148000 }, { dish_id: 7, price: 188000 }, { dish_id: 8, price: 260000 },
    { dish_id: 9, price: 499000 }, { dish_id: 10, price: 690000 }, { dish_id: 11, price: 690000 }, { dish_id: 12, price: 248000 },
    { dish_id: 13, price: 890000 }, { dish_id: 14, price: 360000 }, { dish_id: 15, price: 98000 }, { dish_id: 16, price: 118000 },
    { dish_id: 17, price: 89000 }, { dish_id: 18, price: 89000 }, { dish_id: 19, price: 1290000 }, { dish_id: 20, price: 990000 }
];

const managerOrAdminStaff = [{ user_id: 1, role_id: 4 }, { user_id: 2, role_id: 3 }];
const regularStaff = [{ user_id: 3, role_id: 2 }, { user_id: 4, role_id: 2 }, { user_id: 14, role_id: 2 }];

// Will be generated by Vouchers SQL block
const vouchers = [
    { voucher_id: 1, discount_type: 'Percent', discount_value: 10 },
    { voucher_id: 2, discount_type: 'Fixed', discount_value: 20000 }
];
const paymentMethods = [
    { method_id: 1, method_name: 'Cash' }, { method_id: 2, method_name: 'Bank Transfer' }, { method_id: 3, method_name: 'MOMO' }
];
const qrMethods = [paymentMethods[1], paymentMethods[2]];
const cashMethod = paymentMethods[0];

// --- IDENTITY POOLS ---
const SURNAMES = [
    { name: 'Nguyễn', weight: 40 }, { name: 'Trần', weight: 15 }, { name: 'Lê', weight: 10 }, { name: 'Phạm', weight: 7 },
    { name: 'Hoàng', weight: 5 }, { name: 'Huỳnh', weight: 5 }, { name: 'Phan', weight: 4 }, { name: 'Vũ', weight: 4 },
    { name: 'Võ', weight: 4 }, { name: 'Đặng', weight: 3 }, { name: 'Bùi', weight: 3 }
];
const MID_NAMES = ['Văn', 'Thị', 'Minh', 'Hữu', 'Thanh', 'Ngọc', 'Quốc', 'Tuấn', 'Đức', 'Phương', 'Bảo', 'Gia'];
const FIRST_NAMES = ['An', 'Bình', 'Châu', 'Dũng', 'Đạt', 'Giang', 'Hùng', 'Hương', 'Khánh', 'Linh', 'Long', 'Mai', 'Nam', 'Nga', 'Phong', 'Quân', 'Sơn', 'Thảo', 'Trang', 'Uyên', 'Vinh', 'Xuân'];
const MOBILE_PREFIXES = ['09', '08', '07', '03', '05'];

function weightedRandom(pool) {
    const totalWeight = pool.reduce((sum, item) => sum + item.weight, 0);
    let random = prng.nextRange(0, totalWeight - 1);
    for (const item of pool) {
        if (random < item.weight) return item;
        random -= item.weight;
    }
    return pool[pool.length - 1];
}

function removeAccents(str) {
    return str.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/đ/g, 'd').replace(/Đ/g, 'D');
}

function generateIdentity(index) {
    const surname = weightedRandom(SURNAMES).name;
    const midname = prng.nextElement(MID_NAMES);
    const firstname = prng.nextElement(FIRST_NAMES);
    const fullName = `${surname} ${midname} ${firstname}`;
    const emailBase = removeAccents(fullName.toLowerCase()).replace(/\s/g, '');
    const email = `${emailBase}${index}@gmail.com`;
    const phone = prng.nextElement(MOBILE_PREFIXES) + prng.nextRange(10000000, 99999999);
    return { fullName, email, phone };
}

// Generate customer pool
const REPEAT_CUSTOMERS = [];
for (let i = 0; i < 500; i++) {
    REPEAT_CUSTOMERS.push(generateIdentity(i + 1));
}

function chunkArray(myArray, chunk_size) {
    let index = 0;
    let arrayLength = myArray.length;
    let tempArray = [];
    for (index = 0; index < arrayLength; index += chunk_size) {
        tempArray.push(myArray.slice(index, index + chunk_size));
    }
    return tempArray;
}

function generateSqlBlock(tableName, columns, values, identityInsert) {
    if (values.length === 0) return '';
    let sql = '';
    if (identityInsert) sql += `SET IDENTITY_INSERT dbo.${tableName} ON;\n`;
    const chunks = chunkArray(values, 999); // SQL Server limit is 1000 rows per INSERT
    for (const chunk of chunks) {
        sql += `INSERT INTO dbo.${tableName} (${columns}) VALUES \n${chunk.join(',\n')};\n`;
    }
    if (identityInsert) sql += `SET IDENTITY_INSERT dbo.${tableName} OFF;\n`;
    sql += 'GO\n\n';
    return sql;
}

export function generateAllData() {
    console.log("Generating Data...");
    let allUsers = [];
    let allProfiles = [];
    let allReservations = [];
    let allOrders = [];
    let allOrderItems = [];
    let allKitchenTickets = [];
    let allPayments = [];
    let allAuditLogs = [];
    let allStaffSchedules = [];
    let allPerformanceReviews = [];
    let allReservationTables = [];

    const endDate = new Date();
    const startDate = new Date();
    startDate.setDate(endDate.getDate() - 365);

    const totalDays = 365;
    let currentDate = new Date(startDate);
    
    let globalOrderId = 1000;
    let globalOrderItemId = 1000;
    let globalKitchenTicketId = 1000;
    let globalReservationId = 1000;
    let globalUserId = 1000;
    
    for (const rc of REPEAT_CUSTOMERS) {
        const userId = globalUserId++;
        rc.userId = userId;
        allUsers.push(`(${userId}, 1, N'${rc.fullName}', N'${rc.email}', '${rc.phone}', N'$2b$10$RIY70dyCRrUSfUJsJGPyluad9hMxx1eYG5vckpjMPxOS/oJvumTz6', 1, 1, '${startDate.toISOString()}')`);
        allProfiles.push(`(${userId}, ${userId}, N'user_${userId}', 0)`);
    }
    
    let dayCounter = 0;
    
    while (currentDate <= endDate) {
        dayCounter++;
        const isWeekend = currentDate.getDay() === 0 || currentDate.getDay() === 6;
        const isFriday = currentDate.getDay() === 5;
        const isSunday = currentDate.getDay() === 0;
        
        let dailyOrderVolume = prng.nextRange(2, 3);
        if (isFriday || isWeekend && !isSunday) dailyOrderVolume = Math.floor(dailyOrderVolume * prng.nextRange(15, 20) / 10.0);
        else if (isSunday) dailyOrderVolume = Math.floor(dailyOrderVolume * 1.3);

        const growthFactor = 1 + (dayCounter / totalDays) * 0.3;
        dailyOrderVolume = Math.floor(dailyOrderVolume * growthFactor);
        
        if (prng.chance(0.02)) dailyOrderVolume = dailyOrderVolume * prng.nextRange(2, 3);
        if (prng.chance(0.05)) dailyOrderVolume = Math.max(1, Math.floor(dailyOrderVolume * 0.5));

        for (let o = 0; o < dailyOrderVolume; o++) {
            const isLunch = prng.chance(0.5);
            let hour, minute = prng.nextRange(0, 59);
            if (isLunch) {
                hour = prng.nextRange(11, 13);
            } else {
                hour = prng.nextRange(18, 21);
                if (isWeekend && prng.chance(0.2)) hour = 22;
            }
            const orderTime = new Date(currentDate);
            orderTime.setHours(hour, minute, 0, 0);

            const isCancelled = prng.chance(0.07);
            const orderStatus = isCancelled ? 'Cancelled' : 'Paid';
            
            let customer;
            if (prng.chance(0.65)) {
                customer = prng.nextElement(REPEAT_CUSTOMERS);
            } else {
                customer = generateIdentity(globalUserId);
                const userId = globalUserId++;
                customer.userId = userId;
                allUsers.push(`(${userId}, 1, N'${customer.fullName}', N'${customer.email}', '${customer.phone}', N'$2b$10$RIY70dyCRrUSfUJsJGPyluad9hMxx1eYG5vckpjMPxOS/oJvumTz6', 1, 1, '${orderTime.toISOString()}')`);
                allProfiles.push(`(${userId}, ${userId}, N'user_${userId}', 0)`);
            }

            const table = prng.nextElement(tables);
            const partySize = prng.nextRange(1, table.capacity);

            const resId = globalReservationId++;
            const resStatus = isCancelled ? 'Cancelled' : 'Completed';
            const endTime = new Date(orderTime.getTime() + 2 * 60 * 60 * 1000);
            allReservations.push(`(${resId}, ${customer.userId}, N'${customer.fullName}', '${customer.phone}', '${orderTime.toISOString()}', '${endTime.toISOString()}', ${partySize}, N'${resStatus}', NULL, '${orderTime.toISOString()}')`);
            allReservationTables.push(`(${resId}, ${table.table_id})`);

            const orderId = globalOrderId++;
            const createdByStaff = prng.nextElement(regularStaff).user_id;
            
            let totalAmount = 0;
            let numItems = prng.nextRange(partySize, partySize * 2);
            let currentItems = [];
            for(let i=0; i<numItems; i++) {
                const dish = prng.nextElement(dishes);
                const qty = prng.nextRange(1, 2);
                const price = dish.price;
                totalAmount += price * qty;
                currentItems.push({ dish, qty, price });
            }

            let discountAmount = 0;
            if (!isCancelled && prng.chance(0.2)) {
                const voucher = prng.nextElement(vouchers);
                if (voucher.discount_type === 'Percent') {
                    discountAmount = totalAmount * (voucher.discount_value / 100.0);
                } else {
                    discountAmount = voucher.discount_value;
                }
                if (discountAmount > totalAmount) discountAmount = totalAmount;
            }
            const serviceCharge = (totalAmount - discountAmount) * 0.05;
            const finalAmount = totalAmount - discountAmount + serviceCharge;

            allOrders.push(`(${orderId}, ${resId}, ${table.table_id}, ${customer.userId}, ${createdByStaff}, NULL, N'Dine In', N'${orderStatus}', ${totalAmount}, ${discountAmount}, ${serviceCharge}, ${finalAmount}, '${orderTime.toISOString()}')`);

            let ktOffsetSeconds = 0;
            for (const item of currentItems) {
                const oiId = globalOrderItemId++;
                const oiStatus = isCancelled ? 'Cancelled' : 'Served';
                allOrderItems.push(`(${oiId}, ${orderId}, ${item.dish.dish_id}, ${item.qty}, ${item.price}, NULL, N'${oiStatus}')`);

                const ktId = globalKitchenTicketId++;
                const sentAt = new Date(orderTime.getTime() + ktOffsetSeconds * 1000);
                const startedAt = new Date(sentAt.getTime() + prng.nextRange(60, 180) * 1000);
                
                let prepSeconds = prng.nextRange(480, 1200);
                if (!isCancelled && prng.chance(0.03)) prepSeconds = prng.nextRange(1000, 1800);
                const readyAt = new Date(startedAt.getTime() + prepSeconds * 1000);

                if (isCancelled) {
                    const cancelledAt = new Date(sentAt.getTime() + prng.nextRange(60, 600) * 1000);
                    allKitchenTickets.push(`(${ktId}, ${oiId}, N'Cancelled', 3, NULL, '${sentAt.toISOString()}', NULL, NULL, '${cancelledAt.toISOString()}')`);
                    if (prng.chance(0.3)) {
                        const mgr = prng.nextElement(managerOrAdminStaff).user_id;
                        const auditJson = JSON.stringify({ old_status: 'Preparing', new_status: 'Cancelled', actor_type: 'manager_override', cancel_reason: 'Guest changed mind' });
                        allAuditLogs.push(`(${mgr}, ${ktId}, N'KitchenTickets', N'KITCHEN_MANAGER_OVERRIDE_CANCEL', N'${auditJson}', '127.0.0.1', '${cancelledAt.toISOString()}')`);
                    }
                } else {
                    allKitchenTickets.push(`(${ktId}, ${oiId}, N'Served', 3, NULL, '${sentAt.toISOString()}', '${startedAt.toISOString()}', '${readyAt.toISOString()}', NULL)`);
                }
                ktOffsetSeconds += 30;
            }

            if (!isCancelled) {
                const payMethod = prng.chance(0.7) ? prng.nextElement(qrMethods) : cashMethod;
                allPayments.push(`(${orderId}, ${payMethod.method_id}, ${finalAmount}, N'Completed', NULL, '${orderTime.toISOString()}', '${orderTime.toISOString()}')`);
            }
        }

        if (prng.chance(1)) {
            for (const s of regularStaff) {
                if (prng.chance(0.8)) {
                    const shiftId = prng.nextRange(1, 2);
                    const uid = s.user_id;
                    const sid = (uid === 2) ? 1 : (uid === 3) ? 2 : (uid === 4) ? 3 : (uid === 5) ? 4 : (uid === 6) ? 5 : (uid === 14) ? 6 : null;
                    allStaffSchedules.push(`(${uid}, ${sid}, ${shiftId}, '${currentDate.toISOString().split('T')[0]}', N'Present', 1, '${currentDate.toISOString()}', '${currentDate.toISOString()}')`);
                }
            }
        }

        if (currentDate.getDate() === 1) {
            for (const s of regularStaff) {
                let rating = prng.chance(0.9) ? prng.nextRange(35, 50)/10.0 : prng.nextRange(20, 30)/10.0;
                // mapping to staff_id
                const uid = s.user_id;
                const sid = (uid === 2) ? 1 : (uid === 3) ? 2 : (uid === 4) ? 3 : (uid === 5) ? 4 : (uid === 6) ? 5 : (uid === 14) ? 6 : null;
                allPerformanceReviews.push(`(${sid}, ${rating}, N'Monthly Review', 1, '${currentDate.toISOString().split('T')[0]}', '${currentDate.toISOString()}')`);
            }
        }
        
        currentDate.setDate(currentDate.getDate() + 1);
    }

    let finalSql = '\n-- ==========================================\n-- REALISTIC 2-YEAR HISTORICAL DATA SEED\n-- ==========================================\n';
    finalSql += generateSqlBlock('UserAccounts', 'user_id, role_id, full_name, email, phone, password_hash, is_active, email_verified, created_at', allUsers, true);
    finalSql += generateSqlBlock('CustomerProfiles', 'customer_id, user_id, username, loyalty_points', allProfiles, true);
    finalSql += generateSqlBlock('Reservations', 'reservation_id, customer_id, contact_name, contact_phone, reservation_start_at, reservation_end_at, guest_count, reservation_status, special_request, created_at', allReservations, true);
    finalSql += generateSqlBlock('ReservationTables', 'reservation_id, table_id', allReservationTables, false);
    finalSql += generateSqlBlock('Orders', 'order_id, reservation_id, table_id, customer_id, created_by_staff_id, qr_session_id, order_type, order_status, subtotal, discount_amount, service_charge, total_amount, created_at', allOrders, true);
    finalSql += generateSqlBlock('OrderItems', 'order_item_id, order_id, dish_id, quantity, unit_price, notes, item_status', allOrderItems, true);
    finalSql += generateSqlBlock('KitchenTickets', 'kitchen_ticket_id, order_item_id, kitchen_status, priority_level, assigned_to_staff_id, sent_at, started_at, ready_at, cancelled_at', allKitchenTickets, true);
    finalSql += generateSqlBlock('Payments', 'order_id, payment_method_id, amount_paid, payment_status, transaction_ref, paid_at, created_at', allPayments, false);
    finalSql += generateSqlBlock('AuditLogs', 'user_id, target_id, target_table, action_name, new_value_json, ip_address, created_at', allAuditLogs, false);
    finalSql += generateSqlBlock('StaffSchedules', 'user_id, staff_id, shift_id, work_date, attendance_status, assigned_by, created_at, updated_at', allStaffSchedules, false);
    finalSql += generateSqlBlock('PerformanceReviews', 'staff_id, rating, notes, reviewed_by, review_date, created_at', allPerformanceReviews, false);
    
    return finalSql;
}

const phuDataSql = `
-- ==========================================
-- PHU TEST DATA OVERRIDE
-- ==========================================
BEGIN TRANSACTION;

DECLARE @CustomerRoleId TINYINT;
SELECT @CustomerRoleId = role_id FROM dbo.Roles WHERE role_name = N'Customer';

-- Ensure phuadmin@phurai.vn stays Admin — never demote it
UPDATE dbo.UserAccounts
SET role_id = 4, is_active = 1, email_verified = 1
WHERE email = N'phuadmin@phurai.vn';

-- Upsert the customer test account
MERGE dbo.UserAccounts AS target
USING (SELECT N'quagphu159@gmail.com' AS email) AS source
ON target.email = source.email
WHEN MATCHED THEN
    UPDATE SET
        role_id        = @CustomerRoleId,
        full_name      = N'Dang Quang Phu',
        is_active      = 1,
        email_verified = 1
WHEN NOT MATCHED THEN
    INSERT (role_id, full_name, email, password_hash, is_active, email_verified, created_at, updated_at)
    VALUES (@CustomerRoleId, N'Dang Quang Phu', source.email,
            N'$2b$10$.s0tXgRsluKKb9rvQOvLB.8Xk6NNncuUhw3EIbrqp70Ap6knasgP6',
            1, 1, SYSDATETIME(), SYSDATETIME());

-- Target ONLY the customer account for all subsequent seed data
DECLARE @PhuUsers TABLE (user_id INT);
INSERT INTO @PhuUsers (user_id)
SELECT user_id FROM dbo.UserAccounts WHERE email = N'quagphu159@gmail.com';


-- CLEAN UP previous seed data to avoid duplicates or index errors
DELETE FROM dbo.OrderItems WHERE order_id IN (SELECT order_id FROM dbo.Orders WHERE customer_id IN (SELECT user_id FROM @PhuUsers));
DELETE FROM dbo.Payments WHERE order_id IN (SELECT order_id FROM dbo.Orders WHERE customer_id IN (SELECT user_id FROM @PhuUsers));
DELETE FROM dbo.Orders WHERE customer_id IN (SELECT user_id FROM @PhuUsers);
DELETE FROM dbo.Reservations WHERE customer_id IN (SELECT user_id FROM @PhuUsers);
DELETE FROM dbo.CustomerVouchers WHERE customer_id IN (SELECT user_id FROM @PhuUsers);
DELETE FROM dbo.LoyaltyTransactions WHERE customer_id IN (SELECT user_id FROM @PhuUsers);

-- 1. Ensure a CustomerProfile exists for the customer account
MERGE dbo.CustomerProfiles AS target
USING @PhuUsers AS source
ON target.user_id = source.user_id
WHEN NOT MATCHED THEN
    INSERT (user_id, username, date_of_birth, gender, country, [language], bio, loyalty_points, preferences)
    VALUES (source.user_id, N'quagphu159', '2004-12-29', N'Male', N'Vietnam', N'Vietnamese', N'CEO & Regular VIP customer.', 1010, N'["VIP area","Window seat","Steak"]');

-- Update loyalty points to 1010 so he has Gold status and can redeem vouchers
-- Also set username to quagphu159 for his Google account
UPDATE target
SET target.loyalty_points = 1010,
    target.username = CASE WHEN ua.email = 'quagphu159@gmail.com' THEN 'quagphu159' ELSE target.username END
FROM dbo.CustomerProfiles target
INNER JOIN @PhuUsers source ON target.user_id = source.user_id
INNER JOIN dbo.UserAccounts ua ON target.user_id = ua.user_id;

-- 2. Insert Loyalty Point Transactions (so the user sees points history)
-- We will insert Earn and Redeem transactions
INSERT INTO dbo.LoyaltyTransactions (customer_id, points, transaction_type, reference_type, description, created_at)
SELECT source.user_id, 350, N'Earn', N'Payment', N'Points earned from order payment', DATEADD(day, -15, GETDATE())
FROM @PhuUsers source;

INSERT INTO dbo.LoyaltyTransactions (customer_id, points, transaction_type, reference_type, description, created_at)
SELECT source.user_id, 760, N'Earn', N'Payment', N'Points earned from premium dining', DATEADD(day, -5, GETDATE())
FROM @PhuUsers source;

INSERT INTO dbo.LoyaltyTransactions (customer_id, points, transaction_type, reference_type, description, created_at)
SELECT source.user_id, -100, N'Redeem', N'VoucherRedeem', N'Redeemed 50K Voucher', DATEADD(day, -2, GETDATE())
FROM @PhuUsers source;

-- 3. Insert Vouchers into CustomerVouchers (so the user has active and used vouchers)
INSERT INTO dbo.CustomerVouchers (customer_id, promotion_id, points_spent, voucher_code, status, redeemed_at, expires_at)
SELECT source.user_id, 4, 100, N'PHU50K_' + CAST(source.user_id AS NVARCHAR(10)), N'active', DATEADD(day, -2, GETDATE()), DATEADD(day, 28, GETDATE())
FROM @PhuUsers source;

-- 4. Insert 6-Month Spread of Reservations, Orders, Payments, and OrderItems
-- This creates a beautiful wave-like curve in the Expenditure chart!

DECLARE @TableId INT;
SELECT TOP 1 @TableId = table_id FROM dbo.RestaurantTables;

DECLARE @AreaId INT;
SELECT TOP 1 @AreaId = area_id FROM dbo.RestaurantAreas;

-- ==========================================
-- MONTH 5 AGO (5 months ago)
-- ==========================================
INSERT INTO dbo.Reservations (customer_id, contact_name, contact_phone, contact_email, preferred_area_id, reservation_start_at, reservation_end_at, guest_count, special_request, deposit_amount, final_total, reservation_status, created_at)
SELECT source.user_id, N'Dang Quang Phu', '0964813966', N'phuadmin@phurai.vn', @AreaId, DATEADD(month, -5, GETDATE()), DATEADD(month, -5, DATEADD(hour, 2, GETDATE())), 4, N'Window seat please', 100000.00, 1489000.00, N'Completed', DATEADD(month, -5, DATEADD(day, -5, GETDATE()))
FROM @PhuUsers source;

INSERT INTO dbo.Orders (reservation_id, table_id, customer_id, order_type, order_status, subtotal, discount_amount, service_charge, total_amount, amount_paid, created_at)
SELECT 
    (SELECT TOP 1 reservation_id FROM dbo.Reservations WHERE customer_id = source.user_id AND DATEPART(month, reservation_start_at) = DATEPART(month, DATEADD(month, -5, GETDATE()))),
    @TableId,
    source.user_id,
    N'Dine In',
    N'Paid',
    1489000.00,
    100000.00,
    50000.00,
    1439000.00,
    1439000.00,
    DATEADD(month, -5, GETDATE())
FROM @PhuUsers source;

INSERT INTO dbo.Payments (order_id, payment_method_id, amount_paid, change_given, payment_status, paid_at, created_at)
SELECT 
    (SELECT TOP 1 order_id FROM dbo.Orders WHERE customer_id = source.user_id AND DATEPART(month, created_at) = DATEPART(month, DATEADD(month, -5, GETDATE()))),
    1, 
    1439000.00,
    0,
    N'Completed',
    DATEADD(month, -5, GETDATE()),
    DATEADD(month, -5, GETDATE())
FROM @PhuUsers source;

INSERT INTO dbo.OrderItems (order_id, dish_id, quantity, unit_price, notes, item_status)
SELECT o.order_id, 13, 1, 890000.00, N'Medium-rare', N'Served'
FROM dbo.Orders o JOIN @PhuUsers pu ON o.customer_id = pu.user_id WHERE DATEPART(month, o.created_at) = DATEPART(month, DATEADD(month, -5, GETDATE()));

INSERT INTO dbo.OrderItems (order_id, dish_id, quantity, unit_price, notes, item_status)
SELECT o.order_id, 9, 1, 499000.00, N'', N'Served'
FROM dbo.Orders o JOIN @PhuUsers pu ON o.customer_id = pu.user_id WHERE DATEPART(month, o.created_at) = DATEPART(month, DATEADD(month, -5, GETDATE()));

INSERT INTO dbo.OrderItems (order_id, dish_id, quantity, unit_price, notes, item_status)
SELECT o.order_id, 15, 1, 98000.00, N'', N'Served'
FROM dbo.Orders o JOIN @PhuUsers pu ON o.customer_id = pu.user_id WHERE DATEPART(month, o.created_at) = DATEPART(month, DATEADD(month, -5, GETDATE()));


-- ==========================================
-- MONTH 4 AGO (4 months ago)
-- ==========================================
INSERT INTO dbo.Reservations (customer_id, contact_name, contact_phone, contact_email, preferred_area_id, reservation_start_at, reservation_end_at, guest_count, special_request, deposit_amount, final_total, reservation_status, created_at)
SELECT source.user_id, N'Dang Quang Phu', '0901000001', N'phuadmin@phurai.vn', @AreaId, DATEADD(month, -4, GETDATE()), DATEADD(month, -4, DATEADD(hour, 2, GETDATE())), 2, N'', 100000.00, 1250000.00, N'Completed', DATEADD(month, -4, DATEADD(day, -5, GETDATE()))
FROM @PhuUsers source;

INSERT INTO dbo.Orders (reservation_id, table_id, customer_id, order_type, order_status, subtotal, discount_amount, service_charge, total_amount, amount_paid, created_at)
SELECT 
    (SELECT TOP 1 reservation_id FROM dbo.Reservations WHERE customer_id = source.user_id AND DATEPART(month, reservation_start_at) = DATEPART(month, DATEADD(month, -4, GETDATE()))),
    @TableId,
    source.user_id,
    N'Dine In',
    N'Paid',
    1250000.00,
    100000.00,
    50000.00,
    1200000.00,
    1200000.00,
    DATEADD(month, -4, GETDATE())
FROM @PhuUsers source;

INSERT INTO dbo.Payments (order_id, payment_method_id, amount_paid, change_given, payment_status, paid_at, created_at)
SELECT 
    (SELECT TOP 1 order_id FROM dbo.Orders WHERE customer_id = source.user_id AND DATEPART(month, created_at) = DATEPART(month, DATEADD(month, -4, GETDATE()))),
    1, 
    1200000.00,
    0,
    N'Completed',
    DATEADD(month, -4, GETDATE()),
    DATEADD(month, -4, GETDATE())
FROM @PhuUsers source;

INSERT INTO dbo.OrderItems (order_id, dish_id, quantity, unit_price, notes, item_status)
SELECT o.order_id, 13, 1, 890000.00, N'', N'Served'
FROM dbo.Orders o JOIN @PhuUsers pu ON o.customer_id = pu.user_id WHERE DATEPART(month, o.created_at) = DATEPART(month, DATEADD(month, -4, GETDATE()));

INSERT INTO dbo.OrderItems (order_id, dish_id, quantity, unit_price, notes, item_status)
SELECT o.order_id, 14, 1, 360000.00, N'', N'Served'
FROM dbo.Orders o JOIN @PhuUsers pu ON o.customer_id = pu.user_id WHERE DATEPART(month, o.created_at) = DATEPART(month, DATEADD(month, -4, GETDATE()));


-- ==========================================
-- MONTH 3 AGO (3 months ago)
-- ==========================================
INSERT INTO dbo.Reservations (customer_id, contact_name, contact_phone, contact_email, preferred_area_id, reservation_start_at, reservation_end_at, guest_count, special_request, deposit_amount, final_total, reservation_status, created_at)
SELECT source.user_id, N'Dang Quang Phu', '0901000001', N'phuadmin@phurai.vn', @AreaId, DATEADD(month, -3, GETDATE()), DATEADD(month, -3, DATEADD(hour, 2, GETDATE())), 5, N'', 200000.00, 2568000.00, N'Completed', DATEADD(month, -3, DATEADD(day, -5, GETDATE()))
FROM @PhuUsers source;

INSERT INTO dbo.Orders (reservation_id, table_id, customer_id, order_type, order_status, subtotal, discount_amount, service_charge, total_amount, amount_paid, created_at)
SELECT 
    (SELECT TOP 1 reservation_id FROM dbo.Reservations WHERE customer_id = source.user_id AND DATEPART(month, reservation_start_at) = DATEPART(month, DATEADD(month, -3, GETDATE()))),
    @TableId,
    source.user_id,
    N'Dine In',
    N'Paid',
    2568000.00,
    200000.00,
    100000.00,
    2468000.00,
    2468000.00,
    DATEADD(month, -3, GETDATE())
FROM @PhuUsers source;

INSERT INTO dbo.Payments (order_id, payment_method_id, amount_paid, change_given, payment_status, paid_at, created_at)
SELECT 
    (SELECT TOP 1 order_id FROM dbo.Orders WHERE customer_id = source.user_id AND DATEPART(month, created_at) = DATEPART(month, DATEADD(month, -3, GETDATE()))),
    1, 
    2468000.00,
    0,
    N'Completed',
    DATEADD(month, -3, GETDATE()),
    DATEADD(month, -3, GETDATE())
FROM @PhuUsers source;

INSERT INTO dbo.OrderItems (order_id, dish_id, quantity, unit_price, notes, item_status)
SELECT o.order_id, 20, 2, 990000.00, N'', N'Served'
FROM dbo.Orders o JOIN @PhuUsers pu ON o.customer_id = pu.user_id WHERE DATEPART(month, o.created_at) = DATEPART(month, DATEADD(month, -3, GETDATE()));

INSERT INTO dbo.OrderItems (order_id, dish_id, quantity, unit_price, notes, item_status)
SELECT o.order_id, 9, 1, 499000.00, N'', N'Served'
FROM dbo.Orders o JOIN @PhuUsers pu ON o.customer_id = pu.user_id WHERE DATEPART(month, o.created_at) = DATEPART(month, DATEADD(month, -3, GETDATE()));

INSERT INTO dbo.OrderItems (order_id, dish_id, quantity, unit_price, notes, item_status)
SELECT o.order_id, 18, 1, 89000.00, N'', N'Served'
FROM dbo.Orders o JOIN @PhuUsers pu ON o.customer_id = pu.user_id WHERE DATEPART(month, o.created_at) = DATEPART(month, DATEADD(month, -3, GETDATE()));


-- ==========================================
-- MONTH 2 AGO (2 months ago)
-- ==========================================
INSERT INTO dbo.Reservations (customer_id, contact_name, contact_phone, contact_email, preferred_area_id, reservation_start_at, reservation_end_at, guest_count, special_request, deposit_amount, final_total, reservation_status, created_at)
SELECT source.user_id, N'Dang Quang Phu', '0901000001', N'phuadmin@phurai.vn', @AreaId, DATEADD(month, -2, GETDATE()), DATEADD(month, -2, DATEADD(hour, 2, GETDATE())), 3, N'', 150000.00, 1857000.00, N'Completed', DATEADD(month, -2, DATEADD(day, -5, GETDATE()))
FROM @PhuUsers source;

INSERT INTO dbo.Orders (reservation_id, table_id, customer_id, order_type, order_status, subtotal, discount_amount, service_charge, total_amount, amount_paid, created_at)
SELECT 
    (SELECT TOP 1 reservation_id FROM dbo.Reservations WHERE customer_id = source.user_id AND DATEPART(month, reservation_start_at) = DATEPART(month, DATEADD(month, -2, GETDATE()))),
    @TableId,
    source.user_id,
    N'Dine In',
    N'Paid',
    1857000.00,
    150000.00,
    80000.00,
    1787000.00,
    1787000.00,
    DATEADD(month, -2, GETDATE())
FROM @PhuUsers source;

INSERT INTO dbo.Payments (order_id, payment_method_id, amount_paid, change_given, payment_status, paid_at, created_at)
SELECT 
    (SELECT TOP 1 order_id FROM dbo.Orders WHERE customer_id = source.user_id AND DATEPART(month, created_at) = DATEPART(month, DATEADD(month, -2, GETDATE()))),
    1, 
    1787000.00,
    0,
    N'Completed',
    DATEADD(month, -2, GETDATE()),
    DATEADD(month, -2, GETDATE())
FROM @PhuUsers source;

INSERT INTO dbo.OrderItems (order_id, dish_id, quantity, unit_price, notes, item_status)
SELECT o.order_id, 7, 1, 188000.00, N'', N'Served'
FROM dbo.Orders o JOIN @PhuUsers pu ON o.customer_id = pu.user_id WHERE DATEPART(month, o.created_at) = DATEPART(month, DATEADD(month, -2, GETDATE()));

INSERT INTO dbo.OrderItems (order_id, dish_id, quantity, unit_price, notes, item_status)
SELECT o.order_id, 13, 1, 890000.00, N'', N'Served'
FROM dbo.Orders o JOIN @PhuUsers pu ON o.customer_id = pu.user_id WHERE DATEPART(month, o.created_at) = DATEPART(month, DATEADD(month, -2, GETDATE()));

INSERT INTO dbo.OrderItems (order_id, dish_id, quantity, unit_price, notes, item_status)
SELECT o.order_id, 10, 1, 690000.00, N'', N'Served'
FROM dbo.Orders o JOIN @PhuUsers pu ON o.customer_id = pu.user_id WHERE DATEPART(month, o.created_at) = DATEPART(month, DATEADD(month, -2, GETDATE()));

INSERT INTO dbo.OrderItems (order_id, dish_id, quantity, unit_price, notes, item_status)
SELECT o.order_id, 18, 1, 89000.00, N'', N'Served'
FROM dbo.Orders o JOIN @PhuUsers pu ON o.customer_id = pu.user_id WHERE DATEPART(month, o.created_at) = DATEPART(month, DATEADD(month, -2, GETDATE()));


-- ==========================================
-- MONTH 1 AGO (1 month ago)
-- ==========================================
INSERT INTO dbo.Reservations (customer_id, contact_name, contact_phone, contact_email, preferred_area_id, reservation_start_at, reservation_end_at, guest_count, special_request, deposit_amount, final_total, reservation_status, created_at)
SELECT source.user_id, N'Dang Quang Phu', '0901000001', N'phuadmin@phurai.vn', @AreaId, DATEADD(month, -1, GETDATE()), DATEADD(month, -1, DATEADD(hour, 2, GETDATE())), 4, N'', 200000.00, 2279000.00, N'Completed', DATEADD(month, -1, DATEADD(day, -5, GETDATE()))
FROM @PhuUsers source;

INSERT INTO dbo.Orders (reservation_id, table_id, customer_id, order_type, order_status, subtotal, discount_amount, service_charge, total_amount, amount_paid, created_at)
SELECT 
    (SELECT TOP 1 reservation_id FROM dbo.Reservations WHERE customer_id = source.user_id AND DATEPART(month, reservation_start_at) = DATEPART(month, DATEADD(month, -1, GETDATE()))),
    @TableId,
    source.user_id,
    N'Dine In',
    N'Paid',
    5279000.00,
    200000.00,
    100000.00,
    5179000.00,
    5179000.00,
    DATEADD(day, -45, GETDATE())
FROM @PhuUsers source;

INSERT INTO dbo.Payments (order_id, payment_method_id, amount_paid, change_given, payment_status, paid_at, created_at)
SELECT 
    (SELECT TOP 1 order_id FROM dbo.Orders WHERE customer_id = source.user_id AND DATEPART(month, created_at) = DATEPART(month, DATEADD(day, -45, GETDATE())) ORDER BY created_at DESC),
    1, 
    5179000.00,
    0,
    N'Completed',
    DATEADD(day, -45, GETDATE()),
    DATEADD(day, -45, GETDATE())
FROM @PhuUsers source;

INSERT INTO dbo.OrderItems (order_id, dish_id, quantity, unit_price, notes, item_status)
SELECT o.order_id, 13, 2, 890000.00, N'', N'Served'
FROM dbo.Orders o JOIN @PhuUsers pu ON o.customer_id = pu.user_id WHERE DATEPART(month, o.created_at) = DATEPART(month, DATEADD(month, -1, GETDATE()));

INSERT INTO dbo.OrderItems (order_id, dish_id, quantity, unit_price, notes, item_status)
SELECT o.order_id, 9, 1, 499000.00, N'', N'Served'
FROM dbo.Orders o JOIN @PhuUsers pu ON o.customer_id = pu.user_id WHERE DATEPART(month, o.created_at) = DATEPART(month, DATEADD(month, -1, GETDATE()));


-- ==========================================
-- CURRENT MONTH (Today / 15 days ago)
-- ==========================================
INSERT INTO dbo.Reservations (customer_id, contact_name, contact_phone, contact_email, preferred_area_id, reservation_start_at, reservation_end_at, guest_count, special_request, deposit_amount, final_total, reservation_status, created_at)
SELECT source.user_id, N'Dang Quang Phu', '0901000001', N'phuadmin@phurai.vn', @AreaId, DATEADD(day, -15, GETDATE()), DATEADD(day, -15, DATEADD(hour, 2, GETDATE())), 4, N'Window seat', 100000.00, 1250000.00, N'Completed', DATEADD(day, -20, GETDATE())
FROM @PhuUsers source;

INSERT INTO dbo.Orders (reservation_id, table_id, customer_id, order_type, order_status, subtotal, discount_amount, service_charge, total_amount, amount_paid, created_at)
SELECT 
    (SELECT TOP 1 reservation_id FROM dbo.Reservations WHERE customer_id = source.user_id AND DATEPART(month, reservation_start_at) = DATEPART(month, DATEADD(day, -15, GETDATE())) AND deposit_amount = 100000.00),
    @TableId,
    source.user_id,
    N'Dine In',
    N'Paid',
    1250000.00,
    100000.00,
    50000.00,
    1200000.00,
    1200000.00,
    DATEADD(day, -15, GETDATE())
FROM @PhuUsers source;

INSERT INTO dbo.Payments (order_id, payment_method_id, amount_paid, change_given, payment_status, paid_at, created_at)
SELECT 
    (SELECT TOP 1 order_id FROM dbo.Orders WHERE customer_id = source.user_id AND DATEPART(month, created_at) = DATEPART(month, DATEADD(day, -15, GETDATE())) AND subtotal = 1250000.00),
    1, 
    1200000.00,
    0,
    N'Completed',
    DATEADD(day, -15, GETDATE()),
    DATEADD(day, -15, GETDATE())
FROM @PhuUsers source;

INSERT INTO dbo.OrderItems (order_id, dish_id, quantity, unit_price, notes, item_status)
SELECT o.order_id, 13, 1, 890000.00, N'', N'Served'
FROM dbo.Orders o JOIN @PhuUsers pu ON o.customer_id = pu.user_id WHERE DATEPART(month, o.created_at) = DATEPART(month, DATEADD(day, -15, GETDATE())) AND o.subtotal = 1250000.00;

INSERT INTO dbo.OrderItems (order_id, dish_id, quantity, unit_price, notes, item_status)
SELECT o.order_id, 14, 1, 360000.00, N'', N'Served'
FROM dbo.Orders o JOIN @PhuUsers pu ON o.customer_id = pu.user_id WHERE DATEPART(month, o.created_at) = DATEPART(month, DATEADD(day, -15, GETDATE())) AND o.subtotal = 1250000.00;


-- Second order this month
INSERT INTO dbo.Reservations (customer_id, contact_name, contact_phone, contact_email, preferred_area_id, reservation_start_at, reservation_end_at, guest_count, special_request, deposit_amount, final_total, reservation_status, created_at)
SELECT source.user_id, N'Dang Quang Phu', '0901000001', N'phuadmin@phurai.vn', @AreaId, DATEADD(day, -5, GETDATE()), DATEADD(day, -5, DATEADD(hour, 2, GETDATE())), 2, N'Anniversary', 200000.00, 2568000.00, N'Completed', DATEADD(day, -10, GETDATE())
FROM @PhuUsers source;

INSERT INTO dbo.Orders (reservation_id, table_id, customer_id, order_type, order_status, subtotal, discount_amount, service_charge, total_amount, amount_paid, created_at)
SELECT 
    (SELECT TOP 1 reservation_id FROM dbo.Reservations WHERE customer_id = source.user_id AND DATEPART(month, reservation_start_at) = DATEPART(month, GETDATE()) AND deposit_amount = 200000.00),
    @TableId,
    source.user_id,
    N'Dine In',
    N'Paid',
    2568000.00,
    200000.00,
    100000.00,
    2468000.00,
    2468000.00,
    DATEADD(day, -5, GETDATE())
FROM @PhuUsers source;

INSERT INTO dbo.Payments (order_id, payment_method_id, amount_paid, change_given, payment_status, paid_at, created_at)
SELECT 
    (SELECT TOP 1 order_id FROM dbo.Orders WHERE customer_id = source.user_id AND DATEPART(month, created_at) = DATEPART(month, GETDATE()) AND subtotal = 2568000.00),
    1, 
    2468000.00,
    0,
    N'Completed',
    DATEADD(day, -5, GETDATE()),
    DATEADD(day, -5, GETDATE())
FROM @PhuUsers source;

INSERT INTO dbo.OrderItems (order_id, dish_id, quantity, unit_price, notes, item_status)
SELECT o.order_id, 20, 2, 990000.00, N'', N'Served'
FROM dbo.Orders o JOIN @PhuUsers pu ON o.customer_id = pu.user_id WHERE DATEPART(month, o.created_at) = DATEPART(month, GETDATE()) AND o.subtotal = 2568000.00;

INSERT INTO dbo.OrderItems (order_id, dish_id, quantity, unit_price, notes, item_status)
SELECT o.order_id, 9, 1, 499000.00, N'', N'Served'
FROM dbo.Orders o JOIN @PhuUsers pu ON o.customer_id = pu.user_id WHERE DATEPART(month, o.created_at) = DATEPART(month, GETDATE()) AND o.subtotal = 2568000.00;

INSERT INTO dbo.OrderItems (order_id, dish_id, quantity, unit_price, notes, item_status)
SELECT o.order_id, 18, 1, 89000.00, N'', N'Served'
FROM dbo.Orders o JOIN @PhuUsers pu ON o.customer_id = pu.user_id WHERE DATEPART(month, o.created_at) = DATEPART(month, GETDATE()) AND o.subtotal = 2568000.00;


-- Upcoming Confirmed Reservation (No Order/Payment yet)
INSERT INTO dbo.Reservations (customer_id, contact_name, contact_phone, contact_email, preferred_area_id, reservation_start_at, reservation_end_at, guest_count, special_request, deposit_amount, final_total, reservation_status, created_at)
SELECT source.user_id, N'Dang Quang Phu', '0901000001', N'phuadmin@phurai.vn', @AreaId, DATEADD(day, 2, GETDATE()), DATEADD(day, 2, DATEADD(hour, 2, GETDATE())), 6, N'Private room', 500000.00, NULL, N'Confirmed', DATEADD(day, -1, GETDATE())
FROM @PhuUsers source;

COMMIT TRANSACTION;
GO
`;

const generatedRealisticData = generateAllData();

// We will append to System_Restaurant.sql, BUT we must make sure we don't duplicate if it was already appended!
let currentContent = fs.readFileSync(sqlFile, 'utf-8');
const marker = '-- ==========================================\n-- REALISTIC 2-YEAR HISTORICAL DATA SEED\n-- ==========================================';

if (currentContent.includes(marker)) {
    console.log("Already seeded! Removing old seed and regenerating...");
    currentContent = currentContent.split(marker)[0];
}

const finalOutput = currentContent.trim() + '\n\n' + generatedRealisticData + '\n' + phuDataSql;

fs.writeFileSync(sqlFile, finalOutput);
console.log("✅ Successfully injected ALL 2-YEAR SEED DATA natively into System_Restaurant.sql!");
