import React from 'react';
import { motion } from 'framer-motion';
import { formatVND } from '@/core/utils/formatCurrency.js';
import OutlineButton from '@/components/common/OutlineButton.jsx';
import { resolveDishImage } from '../data/menuAssets.js';
import '../styles/liquidGlass.css';


export default function AIDishRecommendations({ recommendedDishes = [], onOpenVisualSearch, onPreviewImage }) {
  const defaultRecommendations = [
    {
      id: 'ai-rec-1',
      name: 'YELLOWTAIL JALAPEÑO',
      price: 320000,
      image_url: '/src/assets/images/menu/menu-yellowtail-jalapeno.jpg',
      aiScore: 98,
      aiReason: 'delicately sliced yellowtail sashimi with touches of garlic puree & jalapeno'
    },
    {
      id: 'ai-rec-2',
      name: 'TORO TARTARE WITH CAVIAR',
      price: 428000,
      image_url: '/src/assets/images/menu/menu-toro-tartare.jpg',
      aiScore: 96,
      aiReason: 'finely chopped bluefin toro topped with ossetra caviar and wasabi soy'
    },
    {
      id: 'ai-rec-3',
      name: 'FLUKE SASHIMI DRY MISO',
      price: 188000,
      image_url: '/src/assets/images/menu/menu-fluke-sashimi.jpg',
      aiScore: 94,
      aiReason: 'yuzu juice, extra virgin olive oil, dry miso, chives'
    },
    {
      id: 'ai-rec-4',
      name: 'NEW STYLE SASHIMI',
      price: 228000,
      image_url: '/src/assets/images/menu/menu-new-style-sashimi.jpg',
      aiScore: 92,
      aiReason: 'seared with hot sesame and olive oil, garlic puree, and ginger'
    },
    {
      id: 'ai-rec-5',
      name: 'SALMON NEW STYLE',
      price: 168000,
      image_url: '/src/assets/images/menu/menu-salmon-new-style.jpg',
      aiScore: 90,
      aiReason: 'thinly sliced fresh salmon lightly seared with hot oil blend'
    },
    {
      id: 'ai-rec-6',
      name: 'SEAFOOD UDON',
      price: 148000,
      image_url: '/src/assets/images/menu/menu-seafood-udon.jpg',
      aiScore: 88,
      aiReason: 'stir-fried thick udon noodles with fresh seafood and spicy broth'
    }
  ];


  const dishesToDisplay = recommendedDishes.length > 0 
    ? recommendedDishes.slice(0, 6).map((d, idx) => ({
        ...d,
        aiScore: d.aiScore || (98 - idx * 2),
        aiReason: d.description || d.aiReason || 'chef signature recommendation'
      }))
    : defaultRecommendations;

  const handleCardImageClick = (dish) => {
    onPreviewImage?.({
      name: dish.name || dish.dish_name,
      image: dish.image_url || dish.image || '/menu/yellowtail-jalapeno.jpg'
    });
  };

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.08
      }
    }
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 18 },
    visible: { opacity: 1, y: 0, transition: { duration: 0.4, ease: [0.16, 1, 0.3, 1] } }
  };

  return (
    <section className="liquid-glass-container" style={{ margin: '24px 0', padding: '32px 28px', background: '#ffffff', borderRadius: '24px', border: '1px solid rgba(208, 197, 186, 0.5)' }}>
      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '16px', marginBottom: '24px' }}>
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
            <h2 style={{ fontSize: '1.4rem', fontWeight: '700', color: 'var(--menu-text, #342716)', margin: 0, letterSpacing: '-0.01em' }}>
              AI Dish Recommendations
            </h2>
            <span className="liquid-score-badge" style={{ background: 'rgba(197, 168, 128, 0.18)', color: 'var(--menu-gold-dark, #6a5e33)', textTransform: 'uppercase', fontSize: '0.7rem', fontWeight: '700' }}>
              Smart AI Match
            </span>
          </div>
          <p style={{ margin: '4px 0 0 0', fontSize: '0.86rem', color: 'var(--menu-body, #4d463d)' }}>
            Curated dishes generated by AI based on sales trends, culinary reviews & flavor pairings
          </p>
        </div>

        {/* Apple Liquid Glass Visual Search Trigger Button */}
        <motion.button
          type="button"
          onClick={onOpenVisualSearch}
          className="apple-liquid-glass-btn"
          whileHover={{ scale: 1.04, y: -2 }}
          whileTap={{ scale: 0.96 }}
        >
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" style={{ color: '#ffffff' }}>
            <circle cx="11" cy="11" r="8"></circle>
            <line x1="21" y1="21" x2="16.65" y2="16.65"></line>
            <path d="M11 8v6M8 11h6"></path>
          </svg>
          Search by AI Image
        </motion.button>

      </div>

      {/* Recommendations Grid with Synchronized Typography */}
      <motion.div 
        variants={containerVariants}
        initial="hidden"
        animate="visible"
        style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fill, minmax(260px, 1fr))',
          gap: '24px'
        }}
      >
        {dishesToDisplay.map((dish) => (
          <motion.div 
            key={dish.id || dish.dish_id || dish.name}
            variants={itemVariants}
            whileHover={{ y: -6, scale: 1.02 }}
            transition={{ type: 'spring', stiffness: 300, damping: 24 }}
            className="apple-liquid-glass-card"
            style={{
              padding: '20px',
              display: 'flex',
              flexDirection: 'column',
              justifyContent: 'space-between',
            }}
          >

            <div>
              {/* Image with zoom-in cursor & Lightbox preview on click */}
              <div 
                onClick={() => handleCardImageClick(dish)}
                style={{ 
                  position: 'relative', 
                  marginBottom: '16px', 
                  borderRadius: '12px', 
                  overflow: 'hidden', 
                  aspectRatio: '4 / 3', 
                  cursor: 'zoom-in',
                  background: '#f5f1ea' 
                }}
              >
                <img 
                  src={resolveDishImage(dish.image_url || dish.image)} 
                  alt={dish.name || dish.dish_name}
                  style={{ width: '100%', height: '100%', objectFit: 'cover', transition: 'transform 0.45s cubic-bezier(0.22, 1, 0.36, 1)' }}
                  className="hover:scale-105"
                />

                <div style={{ position: 'absolute', top: '10px', right: '10px', pointerEvents: 'none' }}>
                  <span className="liquid-score-badge" style={{ background: 'rgba(15, 23, 42, 0.85)', color: '#ffffff', fontSize: '0.72rem', backdropFilter: 'blur(8px)' }}>
                    {dish.aiScore}% AI Match
                  </span>
                </div>
              </div>

              {/* Title matching site menu-item__name font & gold color */}
              <h3 
                onClick={() => handleCardImageClick(dish)}
                style={{ 
                  fontSize: '1rem', 
                  fontWeight: '600', 
                  color: 'var(--menu-gold, #9b845e)', 
                  margin: '0 0 6px 0', 
                  textTransform: 'uppercase', 
                  letterSpacing: '1.5px', 
                  lineHeight: '1.4',
                  cursor: 'pointer'
                }}
              >
                {dish.name || dish.dish_name}
              </h3>

              {/* Description matching site menu-item__desc font & muted color */}
              <p style={{ fontSize: '0.84rem', fontWeight: '400', color: 'var(--menu-body, #4d463d)', margin: '0 0 16px 0', lineHeight: '1.4', letterSpacing: '0.14px' }}>
                {dish.aiReason}
              </p>
            </div>

            {/* Price matching site menu-item__price font */}
            <div style={{ display: 'flex', alignItems: 'center', marginTop: 'auto', paddingTop: '8px' }}>
              <span className="menu-card__price" style={{ fontSize: '1.1rem', fontWeight: '800', fontFamily: 'var(--font-body, "Hanken Grotesk", system-ui, sans-serif)', color: 'var(--menu-text, #342716)' }}>
                {formatVND(dish.price)}
              </span>
            </div>

          </motion.div>
        ))}
      </motion.div>
    </section>
  );
}
