services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Phudeptrai@"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - DB_SERVER=db
    ports:
      - "80:5001"
      - "5001:5001"
    depends_on:
      - db

volumes:
  mssql_data:
